// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attribute': string;
  'responseItem': string;
}
export const cssExports: CssExports;
export default cssExports;
