// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animation': string;
  'emptyResBox': string;
  'errorBox': string;
  'errorMessage': string;
  'linkbox': string;
  'resBox': string;
}
export const cssExports: CssExports;
export default cssExports;
